GET http://localhost:3000/pagos

###
GET http://localhost:3000/pagos/1

###
POST http://localhost:3000/pagos
Content-Type: application/json

{
  "monto": 1,
  "metodo": "efectivo",
  "fecha": "2026-04-13T10:00:00Z",
  "pedidoId": 2
}

###
DELETE http://localhost:3000/pagos/16

###