GET  http://localhost:3000/productos

###
POST http://localhost:3000/productos
Content-Type: application/json

{
  "nombre": "Maqueta de Torta",
  "descripcion": "Torta de plastaformo",
  "precio": "100.00",
  "estado": "activo",
  "tipo": "decoracion",
  "categoriaId": 2
}

###
GET  http://localhost:3000/productos/2

###
PATCH  http://localhost:3000/productos/3
Content-Type: application/json

{
  "nombre": "Torta de Chocolate",
  "descripcion": "Torta de chocolate con relleno de crema",
  "precio": "50.00",
  "estado": "activo",
  "tipo": "postre",
  "categoriaId": 1
}


###
DELETE http://localhost:3000/productos/2