GET  http://localhost:3000/user
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInVzZXJuYW1lIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTc4MTAxNjcwMywiZXhwIjoxNzgxMDIwMzAzfQ.iRYk8uMZTjtiwf6kR2NNmPolWBOe8wh9-k2vdycgq3Q

###
POST http://localhost:3000/user
Content-Type: application/json
////Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInVzZXJuYW1lIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTc4MTAxNjcwMywiZXhwIjoxNzgxMDIwMzAzfQ.iRYk8uMZTjtiwf6kR2NNmPolWBOe8wh9-k2vdycgq3Q

{
  "nombre": "jhovana",
  "email": "jhov@gmail.com",
  "password": "AidanFive5."
}

####
GET http://localhost:3000/user/1

###
PATCH http://localhost:3000/user/2
Content-Type: application/json
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsInVzZXJuYW1lIjoiYWRtaW5pc3RyYWRvciIsImlhdCI6MTc4MTEzNzA0NSwiZXhwIjoxNzgxMTQwNjQ1fQ.2CbZi-zUsNCAOPVJ06fk0AznFtFIf_2j1tFEOifr5Kg

{
  "nombre": "jhovana alejo",
  "email": "jhovi@gmail.com",
  "password": "AidanFive5.."
}

####
DELETE http://localhost:3000/user/6
